server {
    listen 8080;
    client_max_body_size 0;
    client_body_temp_path /data/webdav/tmp;

    location /dav/ {
        root /data/webdav;
        dav_methods PUT DELETE MKCOL;
        create_full_put_path on;
        dav_access user:rw group:rw all:r;
        sendfile on;
        aio threads;
        directio 4m;
        output_buffers 2 1m;
        tcp_nopush on;
    }
}